export const CHECK_STUDENT = "CHECK_STUDENT";
export const ADD_STUDENT = "ADD_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const FILTER_STUDENT = "FILTER_STUDENT";
export const BACKLIST_STUDENT = "BACKLIST_STUDENT";
